language: php

php:
  - 5.4
  - 5.5
  - 5.6

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
